# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Response1',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='game',
            name='Response2',
            field=models.CharField(max_length=3),
        ),
    ]
