# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20160522_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Response1',
            field=models.CharField(max_length=3, verbose_name='Response1'),
        ),
    ]
