# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_questions_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='name',
            field=models.CharField(default=b'question', max_length=15),
        ),
    ]
