# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
